export const URLS = {
  login: "/api/v1/student/login/",
  register: "/api/v1/student/register/",
  studentProfile: "/api/v1/student/profile/",
  olimpiadaQuizList: "/api/v1/quiz/sciences/list/",
  quizTest: "/api/v1/quiz/quizzes/",
  submitAnswers: "/api/v1/quiz/submit-quiz-result/",
  recieveCode: "/api/v1/student/verify-sms/",
  resultQuiz: "/api/v1/quiz/result/list/",
  resendSMSCode: "/api/v1/student/resend-sms-code/",
  forgetPassword: "/api/v1/student/forgot-password/",
  newPassword: "/api/v1/student/reset-password/",
  registerDate: "/api/v1/student/register_date/",
  resendSMSCodeForget: "/api/v1/student/verify-sms-code/",
  faqs: "/faqs/",
  networkings: "/networking/",
  documents: "/olimpiada-about/",
  ofertas: "/nizom/",
  banner: "/banner/",
  beforeReminder: "/before_test_reminder/",
  afterReminder: "/after_test_reminder/",
};
